// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateAccountRes interface {
	createAccountRes()
}

type CreateOrganizationRes interface {
	createOrganizationRes()
}

type DeleteAccountRes interface {
	deleteAccountRes()
}

type DeleteOrganizationRes interface {
	deleteOrganizationRes()
}

type ListAccountRes interface {
	listAccountRes()
}

type ListOrganizationRes interface {
	listOrganizationRes()
}

type ReadAccountRes interface {
	readAccountRes()
}

type ReadOrganizationRes interface {
	readOrganizationRes()
}

type UpdateAccountRes interface {
	updateAccountRes()
}

type UpdateOrganizationRes interface {
	updateOrganizationRes()
}
