// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

var _ Handler = UnimplementedHandler{}

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

// CreateAccount implements createAccount operation.
//
// Creates a new Account and persists it to storage.
//
// POST /accounts
func (UnimplementedHandler) CreateAccount(ctx context.Context, req CreateAccountReq) (r CreateAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrganization implements createOrganization operation.
//
// Creates a new Organization and persists it to storage.
//
// POST /organizations
func (UnimplementedHandler) CreateOrganization(ctx context.Context, req CreateOrganizationReq) (r CreateOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAccount implements deleteAccount operation.
//
// Deletes the Account with the requested ID.
//
// DELETE /accounts/{id}
func (UnimplementedHandler) DeleteAccount(ctx context.Context, params DeleteAccountParams) (r DeleteAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrganization implements deleteOrganization operation.
//
// Deletes the Organization with the requested ID.
//
// DELETE /organizations/{id}
func (UnimplementedHandler) DeleteOrganization(ctx context.Context, params DeleteOrganizationParams) (r DeleteOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAccount implements listAccount operation.
//
// List Accounts.
//
// GET /accounts
func (UnimplementedHandler) ListAccount(ctx context.Context, params ListAccountParams) (r ListAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrganization implements listOrganization operation.
//
// List Organizations.
//
// GET /organizations
func (UnimplementedHandler) ListOrganization(ctx context.Context, params ListOrganizationParams) (r ListOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadAccount implements readAccount operation.
//
// Finds the Account with the requested ID and returns it.
//
// GET /accounts/{id}
func (UnimplementedHandler) ReadAccount(ctx context.Context, params ReadAccountParams) (r ReadAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadOrganization implements readOrganization operation.
//
// Finds the Organization with the requested ID and returns it.
//
// GET /organizations/{id}
func (UnimplementedHandler) ReadOrganization(ctx context.Context, params ReadOrganizationParams) (r ReadOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAccount implements updateAccount operation.
//
// Updates a Account and persists changes to storage.
//
// PATCH /accounts/{id}
func (UnimplementedHandler) UpdateAccount(ctx context.Context, req UpdateAccountReq, params UpdateAccountParams) (r UpdateAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrganization implements updateOrganization operation.
//
// Updates a Organization and persists changes to storage.
//
// PATCH /organizations/{id}
func (UnimplementedHandler) UpdateOrganization(ctx context.Context, req UpdateOrganizationReq, params UpdateOrganizationParams) (r UpdateOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}
