name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  openapi-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: validate
      run: npm ci

    - name: bundle
      run: npm run build

    - name: add schema-viz.html
      run: cp ./ent/schema-viz.html ./docs/schema-viz.html

    - name: add nojekyll
      run: touch ./docs/.nojekyll

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
